local utils = require("needdis.utils")
local config = require("needdis.config")

local eq = assert.are.equal

describe("needdis.utils", function()
	it("strip trims whitespace", function()
		eq("hello", utils.strip("  hello  "))
		eq("hello", utils.strip("\thello\t"))
		eq("hello", utils.strip("hello"))
	end)
	it("checks if is task", function()
		eq(true, utils.is_task(" Some task"), true)
		eq(true, utils.is_task(config.options.icons.done .. " task"))
		eq(false, utils.is_task("TODO"))
		eq(false, utils.is_task(config.options.messages.completed_status_header))
	end)
	it("check if completed task", function()
		eq(true, utils.is_done_task(config.options.icons.done .. " task"))
		eq(false, utils.is_done_task(" task"))
		eq(false, utils.is_done_task("test"))
	end)
	it("get title from line", function()
		eq("task", utils.get_title_from_line(" task"))
		eq("task", utils.get_title_from_line(config.options.icons.done .. " task"))
		eq("task", utils.get_title_from_line("task"))
	end)
end)
